### ISSUE TITLE
Verify our EXIF geo encoding code

### ISSUE THREAD

**Issue by benhylau** [starlinglab/starling-integrity-api#21]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Verify that we are generating valid EXIF and the transformed lat long is accurate.  

1. Note GPS (lat, long) of a an image in Starling Capture.
2. Take the image thru our system, take the EXIF block in C2PA and insert them into the image (or any image) with some exif tool.
3. Put the photo thru some photo locator service and make sure we map to same place as (1).

See: https://github.com/starlinglab/starling-capture-api/pull/13/files#r768884772

## To Do

- [x] Verify a photo

**Comment by benhylau** [comment]
This verification would be quite important for BCN. Bumping 🆙

**Comment by anaulin** [comment]
I believe I have verified our conversion is correct, using sample data from this Slack thread (https://starlinglabhq.slack.com/archives/C02LDUFLSR2/p1643335152553089?thread_ts=1643241541.088700&cid=C02LDUFLSR2).

**Steps**

1. Install `exiftool` CLI downloaded from https://exiftool.org/

2. Using `exiftool`, add the sample GPS data from our assertion into an image:
```
$ exiftool -gpslatituderef=N -gpslatitude="38/1 8/1 6506012611690103/281474976710656" -gpslongituderef=W -gpslongitude="121/1 16/1 5536331316921893/281474976710656" ~/Desktop/cc-kitten-with-exif.jpg
```

3. Double-check with `exiftool` that the data has been written to the image:
```
$ exiftool ~/Desktop/cc-kitten-with-exif.jpg | grep GPS
GPS Version ID                  : 2.3.0.0
GPS Latitude Ref                : North
GPS Longitude Ref               : West
GPS Latitude                    : 38 deg 1' 8.00" N
GPS Longitude                   : 121 deg 1' 16.00" W
GPS Position                    : 38 deg 1' 8.00" N, 121 deg 1' 16.00" W
```

4. Upload the photo into Google Photos (https://photos.google.com), and use the Google Photos UI to inspect the geolocation:
![Screen Shot 2022-01-28 at 1 20 06 PM](https://user-images.githubusercontent.com/6729309/151623393-b6dc54be-a275-485b-aa73-86f09de9d273.png)

5. Clicking on the little map in Google Photos takes us to: https://www.google.com/maps/place/38%C2%B001'08.0%22N+121%C2%B001'16.0%22W/@38.1459006,-121.2271048,11z/data=!4m5!3m4!1s0x0:0xe734edef4ab321d8!8m2!3d38.0188889!4d-121.0211111

This points to a place on the southeast of Lodi, which I believe is the intended location. @benhylau can you confirm (or deny) that this looks correct?

**Comment by YurkoWasHere** [comment]
Looks like we are missing resolution on this test

`38/1 8/1 6506012611690103/281474976710656`
which is identified as 

`38/ Hours` `8/1 Minutes` `6506012611690103/281474976710656 Seconds`

`38 deg 1' 8.00" N` only shows `Hours` and `minutes` and has `0` for seconds.

This is like rounding 2.63132 to 2.63, its right but not accurate.

I'm curious to see if the seconds is correct. 

Although keeping in mind that that GPS is not accurate inside, and the WiFi has a large range for error, so i don't know how accurate we **needs** to be.

**Comment by YurkoWasHere** [comment]
Reproduced @anaulin 's result but I'm still still not happy with lack of precision in the test.

I have confirmed exittool can store better precision by manually converting my result to decimal and using `-gpslatitude="38.13975389"` to update the phone. Result was  `38 deg 8' 23.11"`

**Comment by YurkoWasHere** [comment]
Reading the EXIF spec the value for Long and Lat are `rational64u`

Running `exiftool.exe cat-test.jpg  -n -v` will give you the raw data 

`GPSLatitude = 38 8 23.11400422 (38/1 8/1 32845/1421)`

With both values now visible, we can confirm the math is simply division.

✅Math of `32845/1421` =  `23.11400422237861` which matches `23.11400422`

**Deeper dive**

Running a more verbose exif `exiftool.exe cat-test.jpg  -n -v -v -v` get  raw hex

```
  | | 2)  GPSLatitude = 38 8 23.11400422 (38/1 8/1 32845/1421)
  | |     - Tag 0x0002 (24 bytes, rational64u[3]):
  | |         00ba: 00 00 00 26 00 00 00 01 00 00 00 08 00 00 00 01 [...&............]
  | |         00ca: 00 00 80 4d 00 00 05 8d                         [...M....]
```
Convert values from HEX to DEC the values check out
✅ `00 00 00 26` / 00 00 00 01 = 38/1
✅ `00 00 00 08` / `00 00 00 01` = 8/1
✅ `00 00 80 4d`  / `00 00 05 8d` = 32845 /  1421

This matches the example in  
![image](https://user-images.githubusercontent.com/39072689/151636160-5b58c836-7c2d-409c-a13a-791c47846a49.png)
[source](https://www.ridgesolutions.ie/index.php/2015/03/05/geotag-exif-gps-latitude-field-format/)

**Inject Hex Editor**
Inject `6506012611690103/281474976710656` into the exif via Hex Editor

Convert DEC = HEX
`6506012611690103` = `17 1D2F 1A9F BE77`
`281474976710656` = `1 0000 0000 0000`

Since we only have 4 bytes these values are to large to put into the exif (looks like they are 8 bytes each instead of 4)
```
0017 1D2F 1A9F BE77 to large to put into the exif
0001 0000 0000 0000 to large to put into the exif
```

Since we are blocked lets try just dropping least significant bytes see how close we can get
```
0017 1D2F -> 1,514,799
0001 0000 ->      65,536
``

Check the math
```
1,514,799/65,536 = 23.1139984130859375  (Expected 23.114 so very close!)
```

Throw it in the hex editor and check

```
| 2)  GPSLatitude = 38 8 23.11399841 (38/1 8/1 1514799/65536)
  | |     - Tag 0x0002 (24 bytes, rational64u[3]):
  | |         00ba: 00 00 00 26 00 00 00 01 00 00 00 08 00 00 00 01 [...&............]
  | |         00ca: 00 17 1d 2f 00 01 00 00                         [.../....]
```

Result is off by ~0.00001

**💭OBSERVATION**

- The EXIF standard examples show x/1 y/1 z/1000 but we get odd large numbers.
- It seems the denominator is using HEX value of 1 0000 0000 0000.
- Maybe this is a bug?  🤔
- Still to large to fit this standard if it was to DEC 😟

**Comment by anaulin** [comment]
Thanks for double-checking, this @YurkoWasHere. Sounds like we are confirming that our math is correct and we are representing the lat/lon we have correctly in exif format in our assertions.

**Comment by YurkoWasHere** [comment]
Our current method of dealing with fractions is to use the fraction function
https://github.com/starlinglab/starling-integrity-api/blob/main/starlingcaptureapi/exif.py#L74

This generates an 8 byte numerator and denominator, however EXIF specs define this is being only 4 bytes in size.

Although the value does calculate properly, it cannot be used inside an EXIF directly. This may also lead to confusion by outside observers.

There is also the thought of using a denominator that is a multiple of 10. This would make the number more recognizable and easily calculable (just move decimal place)

We can

1) Leave it as is - it does resolve to the correct value
2) Limit the size of the value down below 4 bytes (4294967295)
3) Use multiple of 10 denominator


Some suggestions from @anaulin 
Using rounding:
```
>>> f = Fraction(122.52346143)
>>> f
Fraction(538863882070597, 4398046511104)
>>> round(f, ndigits=8)
Fraction(12252346143, 100000000)
```
Using denominator limiting:
```
>>> f = Fraction(122.52346143)
>>> f
Fraction(538863882070597, 4398046511104)
>>> f.limit_denominator(4294967295)
Fraction(250367563719, 2043425486)
```
Not use fractions at all
```
(n * 10e8, 10e8)
```

Loss of precision: This will loose a bit of precision, however with the amount of GPS error (+/- 4 m), it is not a significant loss.  We are talking in the range of CM maybe even MM.

**Comment by YurkoWasHere** [comment]
✅External Test confirmation

- On a android phone checked google maps for position
- Took Picture and sent it through starling integrity app
- Decoded C2PA GPS coordinates
- Entered them into google maps and confirmed visually position looked identical as initial check

**Comment by benhylau** [comment]
We decided to do this:

```
>>> f = Fraction(122.52346143)
>>> f
Fraction(538863882070597, 4398046511104)
>>> round(f, ndigits=8)
Fraction(12252346143, 100000000)
```
